import Head from 'next/head'
import profileimage from "../component/image/demo.jpg"
import Image from "next/image"
export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <div className="sticky flex shadow py-5 justify-between px-12">
          <div>
            Navbar
          </div>
        <div>
          Menu
        </div>
        </div>
      </nav>
      <main className="flex flex-wrap">
          <div className="w-1/2">
            <div className="flex flex-col gap-5 my-28 mx-20 justify-center ">
               <div className="text-3xl font-serif pt-8 tracking-wider font-semibold border-t-2 border-blue-300"> {`Hi! I'm Mauliksinh parmar`}</div>
               <div className="font-mono ">Photography is a way of feeling, of touching, of loving. What you have caught on film is captured forever. It remembers little things, long after you have forgotten everything.
              <div className="flex gap-2 my-8 w-28 ">
                <label>
                <Image src={require("../component/image/instagram.png")}  className="cursor-pointer" alt="Instagram"/>
                </label>
                <label>
                <Image src={require("../component/image/github.png")} className="cursor-pointer" alt="github"/>
                </label>
                <label>
                <Image src={require("../component/image/gmail.png")} className="cursor-pointer" alt="gmail"/>
                </label>
                <label>
                <Image src={require("../component/image/linkedin.png")} className="cursor-pointer" alt="linkedin"/>
                </label>
              </div>
            </div>
          
            </div>
          </div>
          <div className="w-1/2 sticky"><Image height={"100%"} src={profileimage} className="h-8" alt="profile photo"/></div>
      </main>

      <footer>
      
      </footer>
    </div>
  )
}
