import { useRouter } from 'next/dist/client/router';
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';

const Navbar = () => {
    const router = useRouter();
    const [menushow, Setmenushow] = useState(false);

    return (
        <>
            {' '}
            <Head>
                <title>Maulik Parmar Portfolio</title>
                <meta
                    name="description"
                    content="Generated by Maulik Parmar Portfolio"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="md:block hidden">
                <div className="sticky top-0 z-50 bg-white shadow flex py-4 justify-between px-20">
                    <div>
                        <div className="w-28 top-1 absolute h-8">
                            <Image
                                src={require('../component/image/signature.png')}
                                alt="icon"
                            />
                        </div>
                    </div>
                    <div className="flex flex-wrap gap-10">
                        <div>
                            <div
                                className={`${
                                    router.pathname == '/'
                                        ? 'border-b-2 border-black'
                                        : ''
                                } cursor-pointer`}
                                onClick={() => router.push('/')}
                            >
                                Home
                            </div>
                        </div>
                        <div>
                            <div
                                className={`${
                                    router.pathname == '/About'
                                        ? 'border-b-2 border-black'
                                        : ''
                                } cursor-pointer`}
                                onClick={() => router.push('/About')}
                            >
                                About
                            </div>
                        </div>
                        <div
                            className={`${
                                router.pathname == '/Blog_self'
                                    ? 'border-b-2 border-black'
                                    : ''
                            } cursor-pointer`}
                            onClick={() => router.push('/Blog_self')}
                        >
                            Blog Self
                        </div>
                        <div
                            className={`${
                                router.pathname == '/Contact'
                                    ? 'border-b-2 border-black'
                                    : ''
                            } cursor-pointer`}
                            onClick={() => router.push('/Contact')}
                        >
                            Contact
                        </div>
                    </div>
                </div>
            </div>
            <div className="md:hidden block">
                <div className="sticky top-0 z-40 justify-center bg-white shadow flex   px-9">
                    <div>
                        <div
                            className="absolute left-0"
                            onClick={() => Setmenushow(!menushow)}
                        >
                            <svg
                                xmlns="http://www.w3.org/2000/svg"
                                className="h-8 absolute top-3.5 left-9 w-8"
                                fill="none"
                                viewBox="0 0 24 24"
                                stroke="currentColor"
                            >
                                <path
                                    strokeLinecap="round"
                                    strokeLinejoin="round"
                                    strokeWidth={2}
                                    d="M4 6h16M4 12h16M4 18h16"
                                />
                            </svg>
                        </div>
                        <div className="w-28  mx-auto ">
                            <Image
                                src={require('../component/image/signature.png')}
                                alt="icon"
                            />
                        </div>
                    </div>
                </div>
                <div
                    className={
                        menushow
                            ? 'bg-white top-0 border-2 border-black z-50 flex gap-5 flex-col fixed w-3/4 h-full'
                            : 'fixed '
                    }
                >
                    <div className="flex justify-between px-7 items-center mt-4">
                        <div className="text-base font-semibold tracking-wider">
                            Menu
                        </div>
                        <div>
                            <svg
                                xmlns="http://www.w3.org/2000/svg"
                                className="h-6 w-6"
                                fill="none"
                                viewBox="0 0 24 24"
                                stroke="currentColor"
                                onClick={() => Setmenushow(false)}
                            >
                                <path
                                    strokeLinecap="round"
                                    strokeLinejoin="round"
                                    strokeWidth={2}
                                    d="M6 18L18 6M6 6l12 12"
                                />
                            </svg>
                        </div>
                    </div>
                    <div className="grid border-t-2 border-black grid-flow-row py-5">
                        <div
                            className="px-6 py-6 hover:bg-black hover:text-white"
                            onClick={() => (
                                Setmenushow(false), router.push('/')
                            )}
                        >
                            Home
                        </div>

                        <div
                            className="px-6 py-6 hover:bg-black hover:text-white"
                            onClick={() => (
                                Setmenushow(false), router.push('/About')
                            )}
                        >
                            About
                        </div>

                        <div
                            className="px-6 py-6 hover:bg-black hover:text-white"
                            onClick={() => (
                                Setmenushow(false), router.push('/Blog_self')
                            )}
                        >
                            Blog Self
                        </div>
                        <div
                            className="px-6 py-6 hover:bg-black hover:text-white"
                            onClick={() => (
                                Setmenushow(false), router.push('/Contact')
                            )}
                        >
                            Contact
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
};

export default Navbar;
